fix: add atc button to all product component in home, list, and recomendation
sirclo-solution/template-framic pull request #117
Opened 2023-03-28 06:54 UTC by DiebrataA

Home
![image](https://user-images.githubusercontent.com/38358288/228150344-7500d1b3-4020-4703-ba5a-293f106ea667.png)
![image](https://user-images.githubusercontent.com/38358288/228150430-60718f1f-9618-478b-bd96-6cc95fb0eb52.png)

List
![image](https://user-images.githubusercontent.com/38358288/228150551-baef0f3b-76f5-4fbc-8563-74eaf65a9cb8.png)
![image](https://user-images.githubusercontent.com/38358288/228150658-2678900d-bbdd-42ae-9601-221b17c98ac8.png)
![image](https://user-images.githubusercontent.com/38358288/228152393-1c256278-d04b-450c-9d4b-8f5f7b945424.png)
![image](https://user-images.githubusercontent.com/38358288/228152445-6df62b59-17b3-46dc-b005-118c0ce7f3b3.png)
![image](https://user-images.githubusercontent.com/38358288/228152535-b9328fa7-7e98-48f0-9bd7-4b9f6918f37e.png)
![image](https://user-images.githubusercontent.com/38358288/228152561-d033185c-9ee4-4a6a-b959-ea0ff7532c1c.png)

List[slug]
![image](https://user-images.githubusercontent.com/38358288/228150892-6cc0f031-7000-49ab-9801-dfbc4c6d2cd6.png)
![image](https://user-images.githubusercontent.com/38358288/228150953-883edec2-7f53-46da-a42e-ba82005b53d1.png)

2023-03-28 10:11 UTC, DiebrataA commented
added POW for cart page
https://drive.google.com/drive/folders/1uZPYrEbdBtWO0cgydSTIKcFs_lXWegFk?usp=share_link

2023-03-28 10:21 UTC, mayun19 requested changes

2023-03-28 10:21 UTC, mayun19 commented on public/scss/components/ChooseVariant.module.scss
> +        @media screen and (max-width: 575px)
pakai mixin varible ga

2023-03-28 10:50 UTC, ardiankristo requested changes

2023-03-28 10:50 UTC, ardiankristo commented on pages/[lng]/index.tsx
> +  const tooglePopupSuccessAddCart = () => setShowPopupSuccessAddCart(!showPopupSuccessAddCart)
Saran buat function yang berfungsi sbg state toggler (bolean state) menerapkan best practice nya yang seperti ini biar ngga ada kemungkinan race condition

https://stackoverflow.com/a/48394541/18537254

Jadi gini
`const tooglePopupSuccessAddCart = () => setShowPopupSuccessAddCart((prevState) => !prevState)`

note: nama variabel `prevState` bebas kalo mau diganti pake nama state nya juga bole

2023-03-29 02:20 UTC, DiebrataA commented
Added Pop up success when add to cart in cart page
![image](https://user-images.githubusercontent.com/38358288/228409741-20fb7eb2-1f6a-4042-884e-58d65c3a20b1.png)

2023-03-29 02:54 UTC, iqbalwijonarko approved these changes

2023-03-29 02:56 UTC, merged