feat(shipping): style shipping discount
sirclo-solution/template-framic pull request #137
Opened 2023-04-25 07:10 UTC by ardiankristo

2023-04-25 08:53 UTC, ardiankristo commented
Add handling for long shipping method text:
![Screenshot from 2023-04-25 15-48-52](https://user-images.githubusercontent.com/40454642/234225418-f8cc4f2c-8606-401b-9f18-cc5fe2c7cca9.png)
![Screenshot from 2023-04-25 15-51-25](https://user-images.githubusercontent.com/40454642/234225480-7db428bd-ffb9-41e0-9969-358e775304bd.png)
![Screenshot from 2023-04-25 15-49-48](https://user-images.githubusercontent.com/40454642/234225519-60deedd6-70d3-48c4-b272-cd23acc8656b.png)
![Screenshot from 2023-04-25 15-49-52](https://user-images.githubusercontent.com/40454642/234225536-6a11bd12-1efd-4d6e-929e-8f963b82d6d3.png)

2023-04-25 09:02 UTC, yohanavitrawati requested changes

2023-04-25 09:02 UTC, yohanavitrawati commented on public/scss/pages/ShippingMethod.module.scss
> +    @media screen and (max-width: 575px) {
tanda { di-enter ya

2023-04-25 09:02 UTC, yohanavitrawati commented on public/scss/pages/ShippingMethod.module.scss
> +    @media screen and (max-width: 575px) {
sama tanda { di-enter ya

2023-04-25 09:37 UTC, yohanavitrawati approved these changes

2023-04-27 03:30 UTC, iqbalwijonarko approved these changes

2023-04-27 07:56 UTC, mayun19 commented
Wording discount nya uppercase to di figma nya nya to all 
![image](https://user-images.githubusercontent.com/16263184/234796971-9940725e-eb15-4c1b-bfdb-beb539416a70.png)


> Figma: [Estimate Shipping](https://www.figma.com/file/TDlhTnv6EtCpPHEi0u7xMS/Framic-v.02?node-id=906%3A16395&t=Ng3WUTzqKN9xCmwD-1) [Shipping Method](https://www.figma.com/file/AMtQECMzDn4EXf4geUmzUI/%F0%9F%9F%A2-%5BVENDOR%5D-Framic?node-id=3962%3A21108&t=oSlY0P3cJjyvEwiw-1) [Order History](https://www.figma.com/file/AMtQECMzDn4EXf4geUmzUI/%F0%9F%9F%A2-%5BVENDOR%5D-Framic?node-id=4070%3A21422&t=HjVTbwH3sffGKCDD-4) [Payment Notif](https://www.figma.com/file/AMtQECMzDn4EXf4geUmzUI/%F0%9F%9F%A2-%5BVENDOR%5D-Framic?node-id=4084%3A21424&t=F3rKnEUcv0g1cCiH-4)
> 
> Product detail shipping estimation: ![Screenshot from 2023-04-25 12-27-16](https://user-images.githubusercontent.com/40454642/234201258-fdbdcd2d-fbe8-4601-80b5-0af467cf3893.png) ![Screenshot from 2023-04-25 12-27-18](https://user-images.githubusercontent.com/40454642/234201287-719a3497-587e-4554-9ba5-15be22f9d139.png)
> 
> Shipping method & order summary box: ![Screenshot from 2023-04-25 12-58-26](https://user-images.githubusercontent.com/40454642/234201331-731e3e11-44bb-47d8-831d-6c3811669077.png) ![Screenshot from 2023-04-25 13-19-41](https://user-images.githubusercontent.com/40454642/234201356-0e9b07c3-0e8f-444b-8749-ddc342da3634.png)
>

2023-04-27 08:09 UTC, mayun19 requested changes

2023-04-27 08:09 UTC, mayun19 commented on public/scss/pages/ShippingMethod.module.scss
> +    @media screen and (max-width: 575px)
use mixin $breakpoint_max_sm

2023-04-27 08:09 UTC, mayun19 commented on public/scss/pages/ShippingMethod.module.scss
> +    @media screen and (max-width: 575px)
idem

2023-04-28 07:41 UTC, ardiankristo commented
![Screenshot from 2023-04-28 14-36-16](https://user-images.githubusercontent.com/40454642/235085700-f6ca5a1c-63a3-4ac8-8f0e-63e8e1c95c17.png)
![Screenshot from 2023-04-28 14-37-59](https://user-images.githubusercontent.com/40454642/235085721-56ab0509-71ac-4d0c-9c4d-55d922de8999.png)

2023-04-28 09:35 UTC, mayun19 approved these changes

2023-04-28 10:17 UTC, merged