Bump Version 2.9.8 to 2.11.1
sirclo-solution/template-framic pull request #23
Opened 2022-04-25 08:51 UTC by rhmnaulia

### Requirement : 
- [x] Bump Version to the latest version of nexus is 2.11.1

### Definition of Done : 

- [x] Implementasi mapPinPoint
- BillingAddress
![image](https://user-images.githubusercontent.com/42644135/165050205-4feea271-c095-46e7-9e3b-669cabf43319.png)
![image](https://user-images.githubusercontent.com/42644135/165050405-a6eb1ea7-845d-4c38-b70a-e68bb20310c6.png)
- ShippingMethod
![image](https://user-images.githubusercontent.com/42644135/165050720-936c0efe-ec20-4ea1-8535-5b02266cd719.png)
![image](https://user-images.githubusercontent.com/42644135/165050790-a28ed121-ab00-4ae8-a9db-19e03e1dddb5.png)
- Account
![image](https://user-images.githubusercontent.com/42644135/165051043-ce2b35b2-f426-4d7e-b893-5f7fd39fc23d.png)
![image](https://user-images.githubusercontent.com/42644135/165051075-ae1c845a-8b0c-410c-9880-28b1ac2d1730.png)

---
- [x] Implementasi DisclaimerMessage
- Login/Register via WaOTP
![image](https://user-images.githubusercontent.com/42644135/165051483-c49604f9-a3b7-4341-ba0f-71e6abb9c465.png)
- Login by email
![image](https://user-images.githubusercontent.com/42644135/165051637-8243d7fc-862d-4524-955f-72fbcc5a83cd.png)
- Register by email
![image](https://user-images.githubusercontent.com/42644135/165051814-d8784aa7-38c6-4f11-b2c7-2318d36b0156.png)
- Contact
![image](https://user-images.githubusercontent.com/42644135/165051915-5bcc7885-3dfa-4cc9-9499-1c8107fd64c1.png)
---
- [x] Implementasi tracker
![image](https://user-images.githubusercontent.com/42644135/165052229-935e8cd8-10d0-4912-a309-055ef63cb529.png)
![image](https://user-images.githubusercontent.com/42644135/165052258-e3c07232-50d7-434c-9649-bd40053b22ec.png)
---
- [x] Rapihin halaman maintenance mode jika WYSWYG nya kosong
![image](https://user-images.githubusercontent.com/42644135/165052629-fb7bd32a-a216-4573-9e4a-e16aa3caaf20.png)
![image](https://user-images.githubusercontent.com/42644135/165052708-260b6f77-b9a4-4afe-8d52-be4223c75543.png)
---
- [x] Implementasi UI membership group
![image](https://user-images.githubusercontent.com/42644135/165053414-83e3f9ee-faaa-4237-9b2a-737929193c0f.png)
---
- [x] Implementasi newsletter v2
![image](https://user-images.githubusercontent.com/42644135/165053945-b0197a62-6491-4991-af3a-aa7fcfaba4d0.png)
![image](https://user-images.githubusercontent.com/42644135/165053990-b09c933b-2845-47da-91f7-bebaa729f961.png)

2022-04-25 09:05 UTC, muhammadanova requested changes

2022-04-25 09:05 UTC, muhammadanova commented on locales/en.json
> +  "disclaimer": {
Boleh ini di sorting

2022-04-25 09:05 UTC, muhammadanova commented on locales/id.json
> +  "disclaimer": {
Boleh ini di sorting

2022-04-25 09:05 UTC, muhammadanova commented on package.json
> +    "@sirclo/nexus": "2.11.1",
Ini udah latest kah?

2022-04-25 09:05 UTC, muhammadanova commented on public/scss/components/MapLocation.module.scss
> +  position: absolute;
Ini bisa pake mixins

2022-04-25 09:05 UTC, muhammadanova commented on public/scss/components/MapLocation.module.scss
>      position: absolute;
Ini bisa pake mixins absolute

2022-04-25 09:05 UTC, muhammadanova commented on public/scss/components/MapLocation.module.scss
>      position: absolute;
ini bisa pake mixins absolute

2022-04-25 09:05 UTC, muhammadanova commented on public/scss/main.scss
> +    display: flex;
ini bisa pake mixins flex

2022-04-25 09:05 UTC, muhammadanova commented on public/scss/pages/Account.module.scss
> +    display: flex;
ini bisa pake mixins flex

2022-04-26 05:40 UTC, muhammadanova approved these changes

2022-04-26 05:41 UTC, Sukmaarifin approved these changes

2022-04-26 05:44 UTC, inezamandha commented
dari aku ada pertanyaan! mohon maap yaa ul
- implementasi mappinpoint

<img width="596" alt="image" src="https://user-images.githubusercontent.com/45808774/165229825-2ea43e90-e77a-4e16-948b-52dba4583672.png">

ku cek disini kayaknya ada yang hilang locales "search location" di search barnya ya? sama gabisa pakai use current location juga kaah?

2022-04-26 05:45 UTC, inezamandha requested changes

2022-04-26 05:45 UTC, inezamandha commented on locales/en.json
> +    "youHave": "You Have",
ini You Have atau You have yaa baiknyaa?

2022-04-26 05:50 UTC, inezamandha requested changes

2022-04-26 05:50 UTC, inezamandha commented on public/scss/components/LoginRegisterOTP.module.scss
> +
kelebihan enternya yaa ul

2022-04-26 05:50 UTC, inezamandha commented on public/scss/components/MapLocation.module.scss
> +  position: absolute;
ini udah pakai mixins tapi masih di declare lagi kah di bawah? gadihapus?

2022-04-26 05:50 UTC, inezamandha commented on public/scss/main.scss
> +
kelebihan enternya ul

2022-04-26 05:50 UTC, inezamandha commented on public/scss/pages/Account.module.scss
> +  }
boleh dikasih enter tidak?

2022-04-26 05:50 UTC, inezamandha commented on public/scss/pages/Account.module.scss
> +  &_points{
boleh dikasih enter juga engga? jadi
&_points
{

2022-04-26 05:50 UTC, inezamandha commented on public/scss/pages/Account.module.scss
ini baiknya &_points::before atau
&_points
{
  &::before
  

ya?

2022-04-26 06:19 UTC, inezamandha requested changes

2022-04-26 06:19 UTC, inezamandha commented on pages/_app.js
> +import { handleWebVitals } from 'lib/handleWebVitals';
kutipnya beda dari yang lain ul. boleh disamakan jadi pakai petik dua? " "

2022-04-26 06:19 UTC, inezamandha commented on public/scss/components/MapLocation.module.scss
> +
kebanyakan enternya ul

2022-04-26 06:19 UTC, inezamandha commented on public/scss/components/Newsletter.module.scss
> +
kebanyakan enternya ul

2022-04-26 06:19 UTC, inezamandha commented on public/scss/components/Newsletter.module.scss
> +    [src$="/"] {
boleh di enter?
jadi
[src$="/"]
{

2022-04-26 06:19 UTC, inezamandha commented on public/scss/main.scss
> +
kebanyakan enternya ul

2022-04-26 06:19 UTC, inezamandha commented on public/scss/main.scss
> +    height: 100vh;
- boleh dienter { nya seperti yang lain?
- line 44 nya boleh dihapus?

2022-04-26 06:19 UTC, inezamandha commented on public/scss/main.scss
> +
kelebihan enternya ul

2022-04-26 06:22 UTC, inezamandha commented
- pertanyaeun dari aku mohon maap kalau panjang ya ini atau rikues ss ss annya lagi
1. maintenance mode kalau WYSIWYG nya ada boleh di attach juga?
2. UI Membership kalau Level bagaimana boleh di attach juga?

2022-04-26 06:27 UTC, inezamandha requested changes

2022-04-26 06:27 UTC, inezamandha commented on public/scss/main.scss
> +    font-size: 16px !important;
gapakai mixin fontSize?

2022-04-26 07:04 UTC, muhammadanova approved these changes
lgtm

2022-04-27 06:31 UTC, inezamandha requested changes

2022-04-27 06:31 UTC, inezamandha commented on public/scss/pages/Account.module.scss
> +    }
boleh diganti engga curly bracketnya di bawah?

&::before
{
      content: ' \2022';
      margin: 0px 6px;
 }

2022-04-27 06:31 UTC, inezamandha commented on public/scss/main.scss
>  .maintenance{
boleh di enter curly bracketnya?

2022-04-27 06:59 UTC, inezamandha approved these changes

2022-04-28 08:47 UTC, merged