feat: add filter shipping, google sso button, and bank logo on coupon
sirclo-solution/template-framic pull request #43
Opened 2022-09-02 06:57 UTC by rhmnaulia

### Google SSO Button
- Desktop
![image](https://user-images.githubusercontent.com/42644135/188074938-36d0e6d7-8711-47a1-b1d7-2a702c5ec11a.png)

- Mobile
![image](https://user-images.githubusercontent.com/42644135/188075172-1d643b4b-2489-4d68-8d8f-4c2db7160c88.png)

- Functionality
![image](https://user-images.githubusercontent.com/42644135/188075277-08f19c41-051d-4afa-b8d2-15ebcbb0244b.png)
![image](https://user-images.githubusercontent.com/42644135/188075356-0f447f49-b8f0-4f9a-b332-d08ed6c19ceb.png)

### Coupon Payment Logo
- Desktop
![image](https://user-images.githubusercontent.com/42644135/188075749-fc6a924c-c121-44e8-ae2d-57d57f5f7a74.png)

- Mobile
![image](https://user-images.githubusercontent.com/42644135/188075867-b33afe83-ea1f-4a5e-a721-998ef97e2da1.png)

- Loader Desktop
![image](https://user-images.githubusercontent.com/42644135/188076000-2303486b-7333-405c-8df2-ab47169d3a82.png)

- Loader Mobile
![image](https://user-images.githubusercontent.com/42644135/188076070-1c868ec3-7042-4966-9899-0e5d986ecbc9.png)

### More Shipping
- Desktop
![image](https://user-images.githubusercontent.com/42644135/188076824-a50397cb-88ed-4f4f-8483-1274283028fd.png)
![image](https://user-images.githubusercontent.com/42644135/188077168-8172567c-3831-4a59-9d38-150180acbdea.png)

- Mobile
![image](https://user-images.githubusercontent.com/42644135/188076900-3e9355ed-ef7a-42db-a403-0091b5c3488a.png)
![image](https://user-images.githubusercontent.com/42644135/188077105-36d63bf3-6887-4f40-9b37-9eff01dfe534.png)

2022-09-02 07:15 UTC, mayun19 commented
> ### Coupon Payment Logo

> ![image](https://user-images.githubusercontent.com/16263184/188079203-bb65e10d-67f8-4d3a-886a-911f0d9b74b2.png)

**tampilan saat ini masi beda dengan figma nya : ada border-top atas logo payment nya dan bagian logo payment nya background color nya terlihat berbeda dengan figma nya. 

lalu wording nya saat ini "GUNAKAN KUPON" sedangkan figma "KODE KUPON"**

**FIGMA** 
![image](https://user-images.githubusercontent.com/16263184/188079068-e03bed12-1621-415d-bb77-b7f45a2fb0f2.png)

2022-09-02 07:18 UTC, mayun19 requested changes
value color nya dibikin variablenaua

2022-09-02 07:22 UTC, mayun19 requested changes

2022-09-02 07:22 UTC, mayun19 commented on public/scss/components/LoginRegisterOTP.module.scss
> +    border: 1px solid #DEE0E3 !important;
value color nya dibikin variable aja

2022-09-02 07:22 UTC, mayun19 commented on public/scss/components/LoginRegisterOTP.module.scss
>      font-size: 0 !important;
ini boleh pake mixin ?

2022-09-02 07:48 UTC, sultanfariz commented on public/scss/components/LoginRegisterOTP.module.scss
> +    br{
mungkin ini bisa dikasih enter biar sama kaya bracket lain

2022-09-02 10:25 UTC, inezamandha commented
boleh minta tolong cek kalau lagi klik kupon, apakah ada loadingnya tidak yaa? Dan juga aman?

in my case dia loadingnya jadi di bagian button gunakan gitu sempet berantakan

2022-09-02 10:36 UTC, inezamandha commented
bagian ini pilih metode pengiriman udah ada desainnya atau kabari ke desainernya belum yaah ul udah oke atau belumnya?

<img width="352" alt="image" src="https://user-images.githubusercontent.com/45808774/188121668-a033985f-18ea-43f2-a410-5dc903e8bf89.png">

**ini baru keinget soalnya punyaku baru hari ini ada desainnya dan diubah gt desainnya jadi berbeda, karena desainer ternyata belum aware dengan fitur ini

2022-09-02 10:43 UTC, inezamandha requested changes

2022-09-02 10:43 UTC, inezamandha commented on locales/en.json
> +    "withEmail": "Sign in Email"
ini bukan Sign in with Email kah?

2022-09-02 10:43 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    background-color: #F2F2F2;
ada mixin tidak inii yang variable?

2022-09-02 10:50 UTC, sultanfariz approved these changes

2022-09-02 10:58 UTC, mayun19 approved these changes

2022-09-05 06:32 UTC, inezamandha approved these changes

2022-09-05 07:40 UTC, merged