feat: bump 2.14, and add new reCAPTCHA
sirclo-solution/template-framic pull request #44
Opened 2022-09-07 09:04 UTC by rhmnaulia

![image](https://user-images.githubusercontent.com/42644135/188838215-8b84d3ca-2878-45f2-878d-69380a3e5dc8.png)

2022-09-07 09:08 UTC, Sukmaarifin approved these changes

2022-09-07 09:14 UTC, virginiaritonga approved these changes

2022-09-07 09:42 UTC, inezamandha commented
- perlu z-index di recaptcha nya enggak yaa? (nanti ini mah diskusi dulu kali ya yang aku tanya di thread juga)
- perlu enggak si recapctha sama WA button gaketimpa?
- boleh SS halaman register & loginnya sekalian yang recaptcha di pojok kanan bawah itu yaa?

2022-09-07 10:17 UTC, rhmnaulia commented
> titip rikuesnya paling yang ss ss annya yaah tapi iya sekaligus nanya buat whatsapp button gaketimpa dan z-index perlu enggak ya?

perlu sepertinya buat jaga2 kalo ada floating widget yang nimpa mungkin

2022-09-07 10:17 UTC, rhmnaulia commented
> request SS tokennya yang di cookies dong aul

udin pack

2022-09-08 04:07 UTC, inezamandha approved these changes

2022-09-08 04:09 UTC, sultanfariz commented on pages/[lng]/register/index.tsx
> +  }, []);
sepertinya tydacc perlu semicolon

2022-09-08 04:09 UTC, sultanfariz commented on pages/[lng]/login/index.tsx
> +  }, []);
sepertinya tydacc perlu semicolon

2022-09-08 04:10 UTC, DiebrataA approved these changes

2022-09-08 04:11 UTC, falmesino commented on components/LoginRegisterOTP/index.tsx
> +  getReCAPTCHAToken?: () => Promise<string>;
```suggestion
  getReCAPTCHAToken?: () => Promise<string>
```

bisa diilangin kan titik koma yang di sini?

2022-09-08 04:11 UTC, inezamandha commented on pages/[lng]/login/index.tsx
> +  }, []);
ho iyak bener yang document.body juga engga kali ya biar seragam

2022-09-08 04:12 UTC, sultanfariz approved these changes

2022-09-08 04:15 UTC, falmesino requested changes
receh

2022-09-08 04:15 UTC, falmesino commented on pages/[lng]/login/index.tsx
>    const linksBreadcrumb = [`${i18n.t("header.home")}`, `${i18n.t("login.title")}`]
```suggestion
  const linksBreadcrumb = [i18n.t("header.home"), i18n.t("login.title")]
```

begitu juga bisa kan ya?

2022-09-08 04:15 UTC, falmesino commented on pages/[lng]/register/index.tsx
> +import { FC, useState, useRef, useEffect} from 'react'
```suggestion
import { 
  FC,
  useState,
  useRef,
  useEffect
} from 'react'
```

legenda mengatakan jika improtnya lebih dari dua (atau 3) dibikin ke bawah.

2022-09-08 04:15 UTC, falmesino commented on pages/[lng]/register/index.tsx
>    const linksBreadcrumb = [`${i18n.t("header.home")}`, `${i18n.t("register.title")}`]
```suggestion
  const linksBreadcrumb = [i18n.t("header.home"), i18n.t("register.title")]
```

dibeginikan jika memungkinkan

2022-09-08 04:19 UTC, falmesino approved these changes

2022-09-08 04:35 UTC, falmesino approved these changes

2022-09-08 06:08 UTC, merged