feat: legal module and disclaimer locales
sirclo-solution/template-framic pull request #45
Opened 2022-09-09 07:35 UTC by feliciakri

Figma
https://www.figma.com/file/AMtQECMzDn4EXf4geUmzUI/%5BVENDOR%5D-Framic?node-id=29%3A1370

![image](https://user-images.githubusercontent.com/8079082/189291148-c558cb7e-5fc4-4783-8bcc-d745ae49ffad.png)
![image](https://user-images.githubusercontent.com/8079082/189291196-bc55b224-889d-4156-9a93-83a2516786f6.png)
![image](https://user-images.githubusercontent.com/8079082/189291244-19194dc7-0568-4d4d-a494-4c40597b6937.png)

![Screenshot from 2022-09-09 13-29-20](https://user-images.githubusercontent.com/8079082/189290882-31d757c5-f0b5-44c2-846b-642ca291ed15.png)
![Screenshot from 2022-09-09 13-29-28](https://user-images.githubusercontent.com/8079082/189290887-2426870c-6fd9-45ee-b153-d08fde3e79d3.png)
![Screenshot from 2022-09-09 13-29-55](https://user-images.githubusercontent.com/8079082/189290890-7c462de1-d099-46ee-a23b-18f14b652d7d.png)
![Screenshot from 2022-09-09 13-30-04](https://user-images.githubusercontent.com/8079082/189290892-d48a8fa1-e310-4d6a-86f2-088e889aa43d.png)
![Screenshot from 2022-09-09 13-30-13](https://user-images.githubusercontent.com/8079082/189290897-09973be9-a516-4ee4-af60-c72c942a1d5d.png)
![Screenshot from 2022-09-09 14-24-10](https://user-images.githubusercontent.com/8079082/189297173-4ad1eaf5-e24e-488d-b191-eab1aa21341e.png)
![Screenshot from 2022-09-09 14-24-42](https://user-images.githubusercontent.com/8079082/189297183-6e9246ec-aca8-4776-bfd7-7294c3b7fa83.png)
![Screenshot from 2022-09-09 14-34-33](https://user-images.githubusercontent.com/8079082/189297191-cf1f628e-7885-4590-8f86-bed01464e502.png)
![Screenshot from 2022-09-09 14-35-22](https://user-images.githubusercontent.com/8079082/189297199-d7592082-eed8-4479-bf28-50b0a4d3ee09.png)

2022-09-09 08:18 UTC, sultanfariz commented on pages/[lng]/legal/[slug].tsx
> +//import PageHeading from "components/PageHeading/PageHeading";
ini lupa dihapus kah?

2022-09-09 08:18 UTC, sultanfariz commented on pages/[lng]/legal/[slug].tsx
> +    const router = useRouter();
indentasinya sedickit tydac rata

2022-09-09 08:18 UTC, sultanfariz commented on pages/[lng]/legal/[slug].tsx
> +		</Layout>
indentasi jugaa

2022-09-09 08:18 UTC, sultanfariz commented on public/scss/pages/Legal.module.scss
> +    {
satu file ini juga indentasinya, kalo di ide localnya gini juga kah atau aman kak?

2022-09-09 08:26 UTC, inezamandha requested changes

2022-09-09 08:26 UTC, inezamandha commented on locales/en.json
> +    "loginByEmail": "By clicking 'Login', I acknowledge and agree to the {TERMS_AND_CONDITIONS} and {PRIVACY_POLICY} of {BRAND_NAME}",
ini masih perlu gak ya mba soalnya enggak ada login by email lagi

2022-09-09 08:26 UTC, inezamandha commented on pages/[lng]/legal/[slug].tsx
> +//import PageHeading from "components/PageHeading/PageHeading";
ini perlu tidak yaa?

2022-09-09 08:26 UTC, inezamandha commented on pages/[lng]/legal/[slug].tsx
> +import { useBrand } from 'lib/useBrand'
ini boleh disamakan pakai kutip dua sama titik koma?

2022-09-09 08:26 UTC, inezamandha commented on pages/[lng]/legal/[slug].tsx
> +            </div>
ini boleh dimundurin maksudnya biar rapi mbaa?

2022-09-09 08:26 UTC, inezamandha commented on public/scss/pages/Legal.module.scss
> +    {
bagian ini di github kelihatannya enggak rapi mba maju mundur maju mundur cantik gitu. apakah padahal di localnya udah rapi atau gimana yaa?

2022-09-09 08:38 UTC, inezamandha commented on locales/en.json
> +    "loginByEmail": "By clicking 'Login', I acknowledge and agree to the {TERMS_AND_CONDITIONS} and {PRIVACY_POLICY} of {BRAND_NAME}",
kulihat login by email masih ada SS nya ya, tapi sepertinya bisa dihapus dan di d-none in soalnya login by email sudah tidak dipakaikan disclaimer message yaa berdasarkan thread yang terbaru itu

2022-09-09 09:04 UTC, inezamandha commented on locales/en.json
>      "contact": "By clicking the 'Submit' button, the Customer expresses approval if the Merchant uses the details provided to contact the Customer about your special request or question. Visit the {P
ini enggak pakai kata kata terbaru kah mba?

2022-09-09 09:06 UTC, inezamandha commented
yang indonesia juga enggak disesuaikan sama kata kata baru kah mba? loginByEmail apakah dihapus tidak?

2022-09-09 09:21 UTC, feliciakri commented on public/scss/pages/Legal.module.scss
> +    {
ini ternyata masalah utf-8 di ubuntu. harusnya fixed

2022-09-09 09:21 UTC, feliciakri commented on pages/[lng]/legal/[slug].tsx
> +		</Layout>
ini ternyata masalah utf-8 di ubuntu. harusnya fixed

2022-09-09 09:21 UTC, feliciakri commented on pages/[lng]/legal/[slug].tsx
> +    const router = useRouter();
ini ternyata masalah utf-8 di ubuntu. harusnya fixed

2022-09-09 09:22 UTC, feliciakri commented on pages/[lng]/legal/[slug].tsx
> +//import PageHeading from "components/PageHeading/PageHeading";
iya lupa wkwk

2022-09-09 09:22 UTC, feliciakri commented on pages/[lng]/legal/[slug].tsx
> +//import PageHeading from "components/PageHeading/PageHeading";
deleted

2022-09-09 09:22 UTC, feliciakri commented on pages/[lng]/legal/[slug].tsx
> +            </div>
ocee

2022-09-09 09:22 UTC, feliciakri commented on public/scss/pages/Legal.module.scss
> +    {
masalah utf-8 di linux

2022-09-09 09:36 UTC, inezamandha commented
one more maapkan ketinggalan mba

boleh ss yang ada di halaman cart engga ya mba? Ada shippingmethod disclaimer message disitu seharusnya di display none-in dulu (belum ada figmanya sad jd gatau tata letak)

mungkin nanti nanti bisa di up yah soalnya sudah lama ini di hide (gatau dari sprint brp)

2022-09-09 09:37 UTC, feliciakri commented
> yang indonesia juga enggak disesuaikan sama kata kata baru kah mba? loginByEmail apakah dihapus tidak?

yang indonesia uda sesuai. loginByEmail akan di hide

2022-09-09 09:38 UTC, inezamandha commented on locales/en.json
>      "contact": "By clicking the 'Submit' button, the Customer expresses approval if the Merchant uses the details provided to contact the Customer about your special request or question. Visit the {P
Ini maksudnya brand name kah mbaa? Kalau iyaa aku sudah ganti di descriptionnya mba samain sama punyaku yaah hehe tadi punyaku udah diganti mba cukma (yang aku up di daily)

Biar gaada brand namenya HEHE
Beloman support nexusnya eee

2022-09-13 03:33 UTC, feliciakri commented
![Screenshot from 2022-09-13 10-27-36](https://user-images.githubusercontent.com/8079082/189801595-c93d951b-d2d9-416e-9375-cac225a844c6.png)
![Screenshot from 2022-09-13 10-25-33](https://user-images.githubusercontent.com/8079082/189801611-46a7af1c-ccc6-45e2-a1d4-90225da8976f.png)

2022-09-13 04:21 UTC, inezamandha approved these changes

2022-09-13 04:21 UTC, inezamandha commented on locales/id.json
> +    "contact": "Dengan menekan tombol 'Kirim', saya mengetahui dan menyetujui {PRIVACY_POLICY} serta mengizinkan {BRAND_NAME} untuk menanggapi pesan saya menggunakan detail kontak yang telah saya ber
brand name nya bisa diganti jadi penjual dulu yaah mba

2022-09-13 04:47 UTC, feliciakri commented on locales/id.json
> +    "contact": "Dengan menekan tombol 'Kirim', saya mengetahui dan menyetujui {PRIVACY_POLICY} serta mengizinkan {BRAND_NAME} untuk menanggapi pesan saya menggunakan detail kontak yang telah saya ber
updated~

2022-09-13 04:59 UTC, sultanfariz approved these changes

2022-09-13 05:38 UTC, merged