feat: Shipping logo on voucher popup
sirclo-solution/template-framic pull request #46
Opened 2022-09-19 10:33 UTC by Sukmaarifin

Mobile
<img width="439" alt="Screen Shot 2022-09-19 at 17 22 19" src="https://user-images.githubusercontent.com/28738321/190999275-a0452ebc-5d04-4098-8342-0735c7b8ee2c.png">

Desktop
<img width="1680" alt="Screen Shot 2022-09-19 at 17 22 05" src="https://user-images.githubusercontent.com/28738321/190999293-5fd7fa1b-7be2-4a4b-a5b9-b4c531a61b8c.png">

2022-09-19 10:36 UTC, muhammadanova approved these changes

2022-09-19 10:38 UTC, DiebrataA requested changes
Sepertinya untuk logo shipper dan bank nya terlalu mepet kiri mba, mungkin bisa dikasih paddingnya di bagian container kupon detailnya kalau di container logonya nggak ngaruh.
![image](https://user-images.githubusercontent.com/38358288/191000098-4d306312-072e-4cb7-8988-f2ddfc68c84a.png)

2022-09-19 10:49 UTC, sultanfariz commented
request ss-an kupon yg dobel shipper sama payment kak

2022-09-20 02:55 UTC, rhmnaulia commented
payment list di couponnya aman kah?

2022-09-20 03:04 UTC, inezamandha commented
ss nya yang terbarunya boleh mba? yang kalau shipping saja atau bank saja sudah enggak mepet kiri lagi?

2022-09-20 03:06 UTC, inezamandha commented
facebook kalau di klik juga aman kan yaa mba bisa diklik(?)

2022-09-20 03:19 UTC, DiebrataA approved these changes

2022-09-20 03:21 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +      margin: 0px 0px 4px 8px
mbole dikasih titik koma mba?

2022-09-20 03:21 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    padding: 4px 4px;
ini padding: 4px(?) boleh mba?

2022-09-20 03:21 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +      font-size: 8px;
ada mixin @include fontSize(8) enggak ya mba?

2022-09-20 03:21 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    @include fixedWidth('370px');
ini ada kytipnya yang bawah enggak ada, penggunaan yang sebenernya bisa ke 22 nya kah mba? atau harusnya gaada kutip?

2022-09-20 03:21 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    & > span
boleh dikasih enter di atasnya & > span mbaa?

2022-09-20 03:21 UTC, sultanfariz approved these changes

2022-09-20 03:29 UTC, inezamandha approved these changes

2022-09-20 04:03 UTC, merged