fix: manual and map address input on placeorder
sirclo-solution/template-framic pull request #49
Opened 2022-09-26 04:44 UTC by virginiaritonga

2022-09-26 08:58 UTC, sultanfariz commented
mau tanya kak soal clear button di search input memang belum di-implement kah? sama wording "Pastikan lokasi....." juga belum yah? makasii
![image](https://user-images.githubusercontent.com/55394860/192235745-b8d3c752-c69d-45bb-9c69-a4dc87674004.png)

2022-09-26 09:08 UTC, sultanfariz requested changes

2022-09-26 09:08 UTC, sultanfariz commented on locales/id.json
> +		"useCurrentLocation": "Gunakan lokasi saat ini"
kelebihan tab jugaa

2022-09-26 09:08 UTC, sultanfariz commented on public/scss/pages/Placeorder.module.scss
> +    white-space: nowrap;
sepertinya sabi pake mixin textOverflow

2022-09-26 09:08 UTC, sultanfariz commented on public/scss/pages/Placeorder.module.scss
> +      left: 50%;
sepertinya juga bisa pake mixin

2022-09-26 10:04 UTC, virginiaritonga commented
> mau tanya kak soal clear button di search input memang belum di-implement kah? sama wording "Pastikan lokasi....." juga belum yah? makasii ![image](https://user-images.githubusercontent.com/55394860/192235745-b8d3c752-c69d-45bb-9c69-a4dc87674004.png)

iyap betul krn dr props nexus dan templett yg udh implement v2 aku cek blm support jugaa utk button dan wording tsb

2022-09-26 10:15 UTC, sultanfariz approved these changes

2022-09-27 02:28 UTC, mayun19 commented
ini wording button di initial statate nya klo di figma nya ada yang "Lanjutkan ke Pengiriman" dan "Lanjutkan" sedangkan yang terimplemen sekarang "Place Order". lalu yang digunakan yang  mana ya ?
![image](https://user-images.githubusercontent.com/16263184/192416038-e6df8fb9-1c92-47b7-8f18-e2c607fb0466.png) 
![image](https://user-images.githubusercontent.com/16263184/192416181-f7658d85-c026-46aa-bab9-86fc4ac2af09.png)

lalu untuk wording button saving popup map nya di figma "Gunakan Lokasi" sedangkan yang terimplement sekarang "Gunakan lokasi ini", yang di gunakan apakah tetep yang saat ini atau bisa di samakan dengan figma nya ?
![image](https://user-images.githubusercontent.com/16263184/192417114-5376c856-d747-4cae-9a76-664c0be33e69.png)

2022-09-27 02:32 UTC, mayun19 commented on public/scss/components/MapLocation.module.scss
> +      width: 18px;
width dan height nya karena value nya sama bisa pakai mixin kah ?

2022-09-27 02:35 UTC, mayun19 requested changes

2022-09-27 02:35 UTC, mayun19 commented on public/scss/components/MapLocation.module.scss
>      width: 100%;
ini juga bisa pake mixin juga kah ?

2022-09-27 02:35 UTC, mayun19 commented on public/scss/components/MapLocation.module.scss
>      background: #fff;
ini bisa pakai color variable kah?

2022-09-27 02:41 UTC, DiebrataA requested changes
changes dikit yaw

2022-09-27 02:41 UTC, DiebrataA commented on public/scss/components/MapLocation.module.scss
>      position: absolute;
ini sepertinya sudah pakai mixin @include absolute di atas, jadi bisa di hapus saja mungkin

2022-09-27 05:33 UTC, virginiaritonga commented
> ini wording button di initial statate nya klo di figma nya ada yang "Lanjutkan ke Pengiriman" dan "Lanjutkan" sedangkan yang terimplemen sekarang "Place Order". lalu yang digunakan yang mana ya ? ![image](https://user-images.githubusercontent.com/16263184/192416038-e6df8fb9-1c92-47b7-8f18-e2c607fb0466.png) ![image](https://user-images.githubusercontent.com/16263184/192416181-f7658d85-c026-46aa-bab9-86fc4ac2af09.png)
> 
> lalu untuk wording button saving popup map nya di figma "Gunakan Lokasi" sedangkan yang terimplement sekarang "Gunakan lokasi ini", yang di gunakan apakah tetep yang saat ini atau bisa di samakan dengan figma nya ? ![image](https://user-images.githubusercontent.com/16263184/192417114-5376c856-d747-4cae-9a76-664c0be33e69.png)

siap sudah diconfirmed designer pakai Lanjutkan ya mbaa 
<img width="375" alt="Screen Shot 2022-09-27 at 12 25 23" src="https://user-images.githubusercontent.com/43097333/192440523-6d544f37-735b-4970-871a-591c8f4491da.png">

2022-09-27 05:57 UTC, DiebrataA approved these changes

2022-09-27 06:31 UTC, mayun19 requested changes
ada tambahan dikit untuk ini ya mba

2022-09-27 06:31 UTC, mayun19 commented on public/scss/components/MapLocation.module.scss
>        background-color: #ededed !important;
ini bisa pakai color variable ?

2022-09-27 06:31 UTC, mayun19 commented on public/scss/components/MapLocation.module.scss
>      position: absolute;
ini bisa di hapus ? soalnya sudah ada di mixin atas

2022-09-27 06:37 UTC, mayun19 approved these changes

2022-09-27 07:28 UTC, merged