Feat: bump version nexus@2.16.1, coupon improvement
sirclo-solution/template-framic pull request #52
Opened 2022-10-06 02:47 UTC by sultanfariz

**Screenshots:**
- Coupon List
![desktop coupon list](https://user-images.githubusercontent.com/55394860/194202646-77acc720-d495-4ecd-8676-11e2219c6d84.png)
![desktop coupon list used](https://user-images.githubusercontent.com/55394860/194202645-994b7008-effb-4ea5-9680-da590a8c02b1.png)
![mobile coupon list](https://user-images.githubusercontent.com/55394860/194202653-99983b4a-f915-4c3d-a7b3-71ce44bce385.png)
![mobile coupon list 2](https://user-images.githubusercontent.com/55394860/194202650-f9d4c544-04bd-4217-9619-37823bea6cbe.png)
![mobile empty coupon](https://user-images.githubusercontent.com/55394860/194202655-baf807d7-8434-461b-9f05-064cc19ac772.png)

- Coupon detail popup
![desktop coupon detail popup](https://user-images.githubusercontent.com/55394860/194202637-ef714b08-2b40-4273-9229-4d26572f757a.png)
![mobile coupon detail popup](https://user-images.githubusercontent.com/55394860/194202648-c883fbd7-cf82-4f0e-9937-759e3193f919.png)

2022-10-06 03:13 UTC, Sukmaarifin commented on components/OrderSummaryBox/index.tsx
> +  // voucherTitleClassName: styles.ordersummary_voucherTitle,
ini boleh dihapus klo engga dipake

2022-10-06 03:13 UTC, Sukmaarifin commented on components/OrderSummaryBox/index.tsx
> +        // isCouponAccordion
ini juga dihapus ajah klo udah ga dipake

2022-10-06 03:13 UTC, Sukmaarifin commented on package.json
> +    "@sirclo/nexus": "2.16.1",
bisa sekalian 2.16.4 ya

2022-10-06 03:39 UTC, mayun19 requested changes

2022-10-06 03:39 UTC, mayun19 commented on components/OrderSummaryBox/index.tsx
> +  // voucherDetailCodeClassName: styles.ordersummary_voucherDetailCode,
ini sudah tidak dipakai? bisa di hapus

2022-10-06 03:39 UTC, mayun19 commented on components/OrderSummaryBox/index.tsx
> +  // voucherTitleClassName: styles.ordersummary_voucherTitle,
ini sudah tidak dipakai? bisa di hapus

2022-10-06 09:00 UTC, mayun19 commented
Font weight pada judul detail popup yang terimplement saat ini sepertinya lebih tebal dari yang ada di figma ? 
> * Coupon detail popup
>   ![desktop coupon detail popup](https://user-images.githubusercontent.com/55394860/194202637-ef714b08-2b40-4273-9229-4d26572f757a.png)
>   ![mobile coupon detail popup](https://user-images.githubusercontent.com/55394860/194202648-c883fbd7-cf82-4f0e-9937-759e3193f919.png)

figma 
![image](https://user-images.githubusercontent.com/16263184/194269106-0dc2982a-dc5a-44ba-a1df-9c3689052626.png)

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    flex-wrap: wrap;
ini ada di mixins bisa diganti jadinya @include flex(row, flex-start, flex-start, true);

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    & > * {
boleh di enter?

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    @media screen and (max-width: $breakpoint_max_md) {
boleh dienter?

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    div[class*="ordersummary_voucherDetailEstimate_"]{
boleh dienter?

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    @media screen and (max-width: $breakpoint_max_sm) {
boleh dienter?

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    @media screen and (max-width: 575px) {
boleh dienter?

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    @media screen and (max-width: $breakpoint_max_sm) {
ini boleh dienter?

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
>      > span {
nitip ini kelihatan belum dienter, tapi bukan dari punyanya sultan hehe bolehh?

2022-10-06 10:16 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +    @media screen and (max-width: 575px) {
ini boleh dienter?

2022-10-07 00:47 UTC, mayun19 approved these changes

2022-10-10 03:09 UTC, Sukmaarifin approved these changes

2022-10-10 03:10 UTC, merged