feat: access token
sirclo-solution/template-framic pull request #61
Opened 2022-11-08 03:28 UTC by ardiankristo

2022-11-08 07:21 UTC, virginiaritonga commented on .env
> +NEXT_PUBLIC_ENABLE_PREMIUM_FEATURES=true
kalau di template lain valuenya false `NEXT_PUBLIC_ENABLE_PREMIUM_FEATURES=false`

2022-11-08 07:21 UTC, virginiaritonga commented on .env
> +IS_PAID=false
variabel ini buat apa yaak?

2022-11-08 07:21 UTC, virginiaritonga commented on .env.staging
> +IS_PAID=true
yg ini jugaa dibutuhinn buat dimana?

2022-11-08 07:21 UTC, virginiaritonga commented on pages/[lng]/account/index.tsx
> +  useAuthToken,
apus aja komanya kl declare paling terakhir, yg di file2 lain juga yah

2022-11-08 07:21 UTC, virginiaritonga commented on pages/[lng]/account/index.tsx
> +  const [brand, ] = await Promise.all([
kl cm brand, jadiin `[ brand ]` aja, yg bawah2 juga yah

2022-11-08 07:21 UTC, virginiaritonga commented on pages/[lng]/blog/[slug].tsx
> +  const [brand, ] = await Promise.all([
const headerImage dimasukin kesini jg yaa
```suggestion
  const [
    brand,
    headerImage
  ] = await Promise.all([
    useBrandCommon(req, params), 
    getBlogHeaderImage(GRAPHQL_URI(req)),
    useAuthToken({req, res, env: process.env})
  ])
```

2022-11-08 07:28 UTC, virginiaritonga commented on pages/[lng]/blog/index.tsx
> +  const [brand, ] = await Promise.all([
sama jugaa headerImage dideclare kesini juga

2022-11-08 07:28 UTC, virginiaritonga commented on pages/[lng]/cart/index.tsx
> +import { useI18n, useCart, useAuthToken } from '@sirclo/nexus'
jadi new lines kalo udh lebih dr 2 import, yg files lain juga yaa
```suggestion
import {
 useI18n,
 useCart, 
 useAuthToken 
} from '@sirclo/nexus'
```

2022-11-08 07:28 UTC, virginiaritonga commented on pages/[lng]/forgot-password/index.tsx
> +import { ResetPassword, useI18n, useAuthToken } from '@sirclo/nexus'
jadi new lines jugaa

2022-11-08 07:28 UTC, virginiaritonga commented on pages/[lng]/index.tsx
> +  const [brand, ] = await Promise.all([
dataBanners dimasukkin kesini jg yaa

2022-11-08 07:30 UTC, virginiaritonga commented on pages/[lng]/product/[slug].tsx
> +  const [brand, ] = await Promise.all([
data yg di atas dimasukkin kesini jugaa

2022-11-08 07:30 UTC, virginiaritonga commented on pages/[lng]/register/index.tsx
> +  const [brand, ] = await Promise.all([
hasGoogleAuth dll dimasukkin kesini jugaa

2022-11-08 07:30 UTC, virginiaritonga commented on pages/[lng]/login/index.tsx
> +  const [brand, ] = await Promise.all([
hasGoogleAuth dll dimasukkin kesini jugaa

2022-11-08 07:32 UTC, ardiankristo commented on .env
> +IS_PAID=false
ini kecuali yang IS_PAID ada di uno sih, saya copas saja

2022-11-08 07:33 UTC, ardiankristo commented on .env.staging
> +IS_PAID=true
sama seperti di atas, tak hapus IS_PAID nya aja ya

2022-11-08 07:45 UTC, falmesino requested changes
request receh tapi sekarung

2022-11-08 07:45 UTC, falmesino commented on pages/[lng]/article/[slug].tsx
> +} from '@sirclo/nexus';
```suggestion
} from '@sirclo/nexus'
```

titik koma-nya dihapus pacc biar seragam
mungkin kalo ada yang di file lain juga sama dibegitukan

2022-11-08 07:45 UTC, falmesino commented on pages/[lng]/article/[slug].tsx
> +  ]);
```suggestion
  ])
```
titik koma-nya dihapus pacc biar seragam
mungkin kalo ada yang di file lain juga sama dibegitukan

2022-11-08 07:45 UTC, falmesino commented on pages/[lng]/gift-card/index.tsx
> +import { GiftCard, useI18n, useAuthToken } from '@sirclo/nexus'
```suggestion
import { 
  GiftCard,
  useI18n,
  useAuthToken
} from '@sirclo/nexus'
```

legenda mengatakan jika improtnya ada 3 atau lebih dibikin ke bawah seperti contoh

berlaku buat yang di file lain jika ada

2022-11-08 07:50 UTC, mayun19 requested changes

2022-11-08 07:50 UTC, mayun19 commented on pages/[lng]/article/[slug].tsx
>    params,
koma nya diakhir params nya dihapus ya pac

2022-11-08 07:50 UTC, mayun19 commented on pages/[lng]/blog/[slug].tsx
> +  useAuthToken,
koma diakhir useAuthToken juga dihapus saja pac, berlaku kesemua ya pac

2022-11-08 07:56 UTC, virginiaritonga approved these changes

2022-11-08 08:10 UTC, tiarss approved these changes

2022-11-10 03:09 UTC, falmesino approved these changes

2022-11-10 03:26 UTC, falmesino requested changes

2022-11-10 03:26 UTC, falmesino commented on pages/[lng]/lookbook/categories/[slug].tsx
> +} from '@sirclo/nexus';
```suggestion
} from '@sirclo/nexus'
```

titik koma

2022-11-10 03:26 UTC, falmesino commented on pages/[lng]/lookbook/categories/index.tsx
> +} from '@sirclo/nexus';
```suggestion
} from '@sirclo/nexus'
```

titik koma

2022-11-10 03:26 UTC, falmesino commented on pages/[lng]/review/[id].tsx
> +    useAuthToken({ req, res, env: process.env }),
```suggestion
    useAuthToken({ req, res, env: process.env })
```

koma di akhirnya mungkin bisa dibumihanguskan ini pacc

2022-11-10 03:26 UTC, falmesino commented on pages/[lng]/contact/index.tsx
> +} from '@sirclo/nexus';
```suggestion
} from '@sirclo/nexus'
```

titik koma

2022-11-10 03:26 UTC, falmesino commented on pages/[lng]/blog/[slug].tsx
>  import { FC, useState } from 'react';
```suggestion
import { FC, useState } from 'react'
```

titik koma dihilangken

2022-11-10 03:26 UTC, falmesino commented on pages/[lng]/blog/[slug].tsx
>  /* library template */
```suggestion
  useAuthToken
} from '@sirclo/nexus'
import Link from 'next/link'
/* library template */
```

titik koma dihilangken

2022-11-10 03:26 UTC, falmesino commented on pages/[lng]/blog/[slug].tsx
>    const { default: lngDict = {} } = await import(`locales/${defaultLanguage}.json`);
```suggestion
  const { slug } = params
  const urlSite = `https://${req.headers.host}/${params.lng}/blog/${slug}`
  const defaultLanguage = brand?.settings?.defaultLanguage || params.lng || 'id'
  const { default: lngDict = {} } = await import(`locales/${defaultLanguage}.json`)
```

biar seragam jangan pake titik koma pacc

2022-11-10 03:38 UTC, falmesino approved these changes

2022-11-10 03:39 UTC, merged