fix: implement persistent layout on pdp
sirclo-solution/template-framic pull request #82
Opened 2023-01-16 05:25 UTC by rafirm29

## Summary
This PR is part of the solution for the flickering issue on Framic's PDP.
Original task: https://phabricator.sirclo.com/T44264

## Screenshot
Note: Screenshots on some pages to check if changes on `Layout` component causes issues
![image](https://user-images.githubusercontent.com/68508069/212604481-027488e6-a88a-47e6-9c6e-d06b2c6bf812.png)
![image](https://user-images.githubusercontent.com/68508069/212604458-f280b239-d267-4c21-a268-b435c5935b71.png)
![image](https://user-images.githubusercontent.com/68508069/212604575-2a1958a9-48a0-4013-9afd-f1cf03625a2f.png)
![image](https://user-images.githubusercontent.com/68508069/212604540-86df5ee7-9966-4b8d-873f-d39bcc1c5824.png)

2023-01-16 06:17 UTC, DiebrataA requested changes

2023-01-16 06:17 UTC, DiebrataA commented on components/Layout/Layout.tsx
> +  useI18n} from '@sirclo/nexus'
coba dibikin gini mungkin ya raff
```suggestion
  useI18n
  } from '@sirclo/nexus'
```

2023-01-16 06:28 UTC, DiebrataA approved these changes

2023-01-16 06:30 UTC, ardiankristo approved these changes

2023-01-16 07:46 UTC, feliciakri commented
kan komponen 'Product" pake type "NextPageWithLayout". bisa ga kom,ponennya implemen "'getLayout' buat ngereturn layout componentnya?

2023-01-16 07:51 UTC, rafirm29 commented
> kan komponen 'Product" pake type "NextPageWithLayout". bisa ga kom,ponennya implemen "'getLayout' buat ngereturn layout componentnya?

Sudah diimplemen kakk `getLayout`-nya seperti ini:
![image](https://user-images.githubusercontent.com/68508069/212624919-c297820d-f1cf-496c-b385-6df9ccdf28f1.png)

Apakah benar ini yg kakak maksudd?

2023-01-17 02:59 UTC, feliciakri approved these changes

2023-01-17 03:02 UTC, merged