refactor: change fixed header to sticky
sirclo-solution/template-framic pull request #87
Opened 2023-02-01 04:19 UTC by rafirm29

## Summary
this is a test for flicker framic solution. Some solutions that will be tested in this PR such as:
- Change header from fixed to sticky (to make scrolling smoother)
- Add webkit style for safari (got from online article regarding Safari scrolling bug)

## Files changed
`components/Header/Header.tsx`
`public/scss/components/Header.module.scss`
`public/scss/components/ProductDetail.module.scss`
Other files were merged from source branch.

2023-02-01 04:58 UTC, mayun19 requested changes

2023-02-01 04:58 UTC, mayun19 commented on pages/[lng]/product/[slug].tsx
> +import { FC, ReactElement, ReactNode } from 'react';
bila ada 3 variable atau lebih dibuat line ke bawah

2023-02-01 04:58 UTC, mayun19 commented on pages/[lng]/product/[slug].tsx
> +import { useI18n, getProductDetail, useAuthToken } from '@sirclo/nexus';
idem

2023-02-01 04:58 UTC, mayun19 commented on pages/[lng]/products/[slug].tsx
> +  FeaturesType,
coma nya ngaruh ga klo di hapus?

2023-02-01 04:58 UTC, mayun19 commented on pages/[lng]/product/[slug].tsx
> +import { useBrand } from 'lib/useBrand';
petik 2 tanpa ; biasanya

2023-02-01 05:16 UTC, mayun19 requested changes

2023-02-01 05:16 UTC, mayun19 commented on pages/_app.js
> +import '@brainhubeu/react-carousel/lib/style.css';
ini juga raf

2023-02-01 05:19 UTC, mayun19 approved these changes

2023-02-02 02:18 UTC, DiebrataA approved these changes

2023-02-02 02:57 UTC, virginiaritonga approved these changes

2023-02-02 07:01 UTC, merged